version: "3"

services:

  mvc:
    image: dlgustavolima/homeoffcine-mvc:latest
    container_name: HomeOffCine-mvc
    build:
      context: ../src
      dockerfile: HomeOffCine.App/Dockerfile 
    restart: always 
    ports:
      - 5000:80 
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=HomeOffCineMVC;User Id=sa;Password=1q2w3e4r@#$;MultipleActiveResultSets=true;TrustServerCertificate=True;
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: HomeOffCine-sqlserver
    environment:
      SA_PASSWORD: "1q2w3e4r@#$"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_USER: sa
    ports:
      - "1433:1433"