apiVersion: v1
kind: Pod
metadata:
  name: homeoffcine
  labels:
    app: homeoffcine
spec:
  containers:
  - name: homeoffcine
    image: dlgustavolima/homeoffcine-mvc:latest
    env:
    - name: ASPNETCORE_ENVIRONMENT
      value: Development
    - name: CUSTOMCONNSTR_DefaultConnection
      value: "Server=database-service;Database=HomeOffCineMVC;User Id=sa;Password=1q2w3e4r@#$;MultipleActiveResultSets=true;TrustServerCertificate=True"
    - name: AppSettings__DatabaseType
      value: SqlServer
    - name: "USE_HTTPS_REDIRECTION"
      value: "false"
    ports:
    - containerPort: 80
  dnsPolicy: ClusterFirst
  restartPolicy: Always