name: Build project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  versionamento:
    runs-on: ubuntu-latest
    name: Versionamento
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch_depth: 0

      - uses: codacy/git-version@2.8.0
        id: version
        with:
            release-branch: main
            prefix: v

      - name: Tag do repositorio
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "::notice:: ${{ steps.version.outputs.version }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git tag -a ${{ steps.version.outputs.version }} -m "Release ${{ steps.version.outputs.version }}"
          git push --tags
        if: github.ref == 'refs/heads/main'
        

  build:
    needs: versionamento
    runs-on: ubuntu-latest
    name: Build Project
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-verion: 8.x
          cache: true
          cache-dependency-path: ./src/HomeOffCine.App/packages.lock.json

      - name: Restore
        run: dotnet restore ./HomeOffCine.sln

      - name: Build
        run: dotnet build --no-restore --configuration Release ./HomeOffCine.sln

      - name: Test
        run: dotnet build --no-build --no-restore ./HomeOffCine.sln --configuration Release --logger trx --results-directory "TestResult"

      - uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-results
          path: TestResults
