name: Build project

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
   
jobs:
    build:
        runs-on: ubuntu-latest
        name: Build Project

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup .NET Core
              uses: actions/setup-dotnet@v4
              with:
                dotnet-verion: '8.x'

            - name: Build
              run: |
                  dotnet restore ./HomeOffCine.sln
                  dotnet build --no-restore ./HomeOffCine.sln
