name: Build project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  versionamento:
    runs-on: ubuntu-latest
    name: Versionamento

    outputs:
      version: $${{ steps.version.output.version }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - uses: codacy/git-version@2.8.0
        id: version
        with:
            release-branch: main
            prefix: v

      - name: Tag do repositorio
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "::notice:: ${{ steps.version.outputs.version }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git tag -a ${{ steps.version.outputs.version }} -m "Release ${{ steps.version.outputs.version }}"
          git push --tags
        if: github.ref == 'refs/heads/main'
        

  build:
    needs: versionamento
    runs-on: ubuntu-latest
    name: Build Project
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
          cache: true
          cache-dependency-path: ./src/HomeOffCine.App/packages.lock.json

      - name: Restore
        run: dotnet restore ./HomeOffCine.sln

      - name: Run dotnet format
        run: dotnet format --verify-no-changes ./HomeOffCine.sln

      - name: Build
        run: dotnet build --no-restore --configuration Release ./HomeOffCine.sln

      - name: Run Unit Tests
        run: dotnet test --no-build --no-restore --configuration Release --logger trx --results-directory TestResults "./test/HomeOffCine.Tests/HomeOffCine.Tests.csproj"

      - uses: actions/upload-artifact@v4
        with:
          name: dotnet-test-results
          path: TestResults

      - name: Publish
        run: dotnet publish ./HomeOffCine.sln --no-restore --no-build --configuration Release --output ./publish

      - name: Upload dotnet artifacts
        uses: actions/upload-artifact@v4
        with:
            name: api
            path: ./publish

  lint:
    needs: versionamento
    runs-on: ubuntu-latest
    name: Lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: github/super-linter@v6
        env:
          DEFAULT_BRANCH: "main"
          VALIDATE_ALL_CODEBASE: "false"
          VALIDATE_YAML: "true"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  dependency-check:
    needs: versionamento
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/dependency-review-action@v4
        with:
          comment-summary-in-pr: always
          base-ref: main
          head-ref: main

  code-security-check:
    needs: versionamento
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: github/codeql-action/init@v3
        name: Initialize CodeQL
        with:
          languages: csharp
          build-mode: autobuild

      - uses: github/codeql-action/analyze@v3
        name: Initialize CodeQL
        with:
          category: "/language:csharp"

  build-docker-image:
    needs: [versionamento, build]
    runs-on: ubuntu-latest

    env:
      version: ${{ needs.versionamento.outputs.version }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with: 
          path: app
          merge-multiple: false

      - name: Build Docker Image
        run: |
          docker build -t ${{vars.DOCKERHUB_REPOSITORY}}/homeoffcine-mvc:${{ env.version }} .

      - name: Tag Docker Image as Latest
        run: |
          docker tag ${{vars.DOCKERHUB_REPOSITORY}}/homeoffcine-mvc:${{ env.version }} ${{vars.DOCKERHUB_REPOSITORY}}/homeoffcine-mvc:latest
        if: github.ref == 'refs/heads/main'

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Docker push
        run: |
          docker push --all-tags homeoffcine-mvc
      